version: '3'

services:
  mariadb:
    image: mariadb:latest 
    container_name: docker-mariadb 
    environment:
      MYSQL_DATABASE: iawe 
      MYSQL_USER: miguel 
      MYSQL_PASSWORD: leugim 
      MYSQL_ROOT_PASSWORD: toor 
    ports:
      - "33306:3306" 
    restart: on-failure
    
  web:
    image: php:7.4-apache 
    container_name: docker-php 
    ports: 
      - "8008:80"
    volumes:
      - ./:/var/www/html
    links:
      - mariadb
