
<!DOCTYPE html>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<html>
    <head>
        <meta charset="UTF-8">
        <title>Practica IAWE</title>
        <link href="../estilos/estilos.css" rel="stylesheet" type="text/css">
        <link rel="preconnect" href="https://fonts.gstatic.com">
        <link href="https://fonts.googleapis.com/css2?family=Potta+One&family=Xanh+Mono&display=swap" rel="stylesheet">
    </head>
    <body>
        <div id="cabecera">
            <div id="logotipo"><img src ="../imagenes/logo.jpg"></div>
            <div id="presentacion">
                <h1> Página oficial de Amantes del Panda</h1>
                <h2> Est. 2020</h2>
            </div>
        </div>
        
