<div class="pie">
    <div class="contenedor_pie">
         <div>
            <h1> Generado para IAWE en IES Paco Molla</h1>
            <h2> &copy; 2020 - 2021 </h2>
         </div>
        <nav>
            <ul>
                <li> <a href="../index.php">Inicio</a></li>
                <li> <a href="../index.php">Login</a></li>
                <li> <a href="../index.php">Registro</a></li>
                <li> <a href="../index.php">Sobre Nosotros</a></li>
            </ul>
        </nav>
        <div class="social">
            <a href="#">Facebook</a>
            <a href="#">Twitter</a>
            <a href="#">Instagram</a>
        </div>   
    </div>
   
</div>

</body>
</html>
